export const employeeConstants = {

    LIST_REQUEST: 'EMPLOYEE_LIST_REQUEST',
    LIST_SUCCESS: 'EMPLOYEE_LIST_SUCCESS',
    LIST_FAILURE: 'EMPLOYEE_LIST_FAILURE',

    REGISTER_REQUEST: 'EMPLOYEE_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'EMPLOYEE_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'EMPLOYEE_REGISTER_FAILURE',

    DELETE_REQUEST: 'EMPLOYEE_DELETE_REQUEST',
    DELETE_SUCCESS: 'EMPLOYEE_DELETE_SUCCESS',
    DELETE_FAILURE: 'EMPLOYEE_DELETE_FAILURE',

    EDIT_REQUEST: 'EMPLOYEE_EDIT_REQUEST',
    EDIT_SUCCESS: 'EMPLOYEE_EDIT_SUCCESS',
    EDIT_FAILURE: 'EMPLOYEE_EDIT_FAILURE',

    EDIT_NAV: 'EMPLOYEE_EDIT_NAV',
    VIEW_NAV:'EMPLOLYEE_VIEW_NAV',

    DETAILS_REQUEST: 'EMPLOYEE_DETAILS_REQUEST',
    DETAILS_SUCCESS: 'EMPLOYEE_DETAILS_SUCCESS',
    DETAILS_FAILURE: 'EMPLOYEE_DETAILS_FAILURE',

    CLEAR_EMPLOYEE_RESP: 'EMPLOYEE_RESP_CLEAR',
    CLEAR_EMPLOYEE_DATA: 'EMPLOYEE_DATA_CLEAR'
}
