export const userConstants = {
    SIGNUP_REQUEST: 'USERS_REGISTER_REQUEST',
    SIGNUP_SUCCESS: 'USERS_REGISTER_SUCCESS',
    SIGNUP_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    SET_SERVER_ERR: 'SET_SERVER_ERR',
    CLEAR_SERVER_ERR: 'CLEAR_SERVER_ERR',


    CLEAR_USER_RESP: 'USER_RESP_CLEAR'

}
